# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Site Title"
description: "Site Description"
subdirectory: ''
baseurl: ''
facebook_image: ''
type: 'article'

# Build settings
markdown: kramdown
timezone: 'America/Los_Angeles'

# Options
permalink: /:title
exclude:
  - 'node_modules'
  - 'bower_components'
  - 'bower.json'
  - 'package.json'
  - 'gulpfile.js'
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.zsh'
keep_files:
sass:
  style: compressed
  sass_dir: _sass
plugins:
  - jekyll-zopfli
  - jekyll-minifier

defaults:
  -
    scope:
      path: '' # empty string for all files
    values:
      layout: 'page'